// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/appointment.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`         // RFC3339
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`             // RFC3339
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Appointment) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Appointment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *CreateAppointmentRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type CreateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentResponse) Reset() {
	*x = CreateAppointmentResponse{}
	mi := &file_proto_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentResponse) ProtoMessage() {}

func (x *CreateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{3}
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_proto_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type DeleteAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_proto_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentResponse) Reset() {
	*x = DeleteAppointmentResponse{}
	mi := &file_proto_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentResponse) ProtoMessage() {}

func (x *DeleteAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{6}
}

var File_proto_appointment_proto protoreflect.FileDescriptor

const file_proto_appointment_proto_rawDesc = "" +
	"\n" +
	"\x17proto/appointment.proto\x12\bschedule\"y\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"X\n" +
	"\x18CreateAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"T\n" +
	"\x19CreateAppointmentResponse\x127\n" +
	"\vappointment\x18\x01 \x01(\v2\x15.schedule.AppointmentR\vappointment\"\x19\n" +
	"\x17ListAppointmentsRequest\"U\n" +
	"\x18ListAppointmentsResponse\x129\n" +
	"\fappointments\x18\x01 \x03(\v2\x15.schedule.AppointmentR\fappointments\"*\n" +
	"\x18DeleteAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteAppointmentResponse2\xab\x02\n" +
	"\x12AppointmentService\x12\\\n" +
	"\x11CreateAppointment\x12\".schedule.CreateAppointmentRequest\x1a#.schedule.CreateAppointmentResponse\x12Y\n" +
	"\x10ListAppointments\x12!.schedule.ListAppointmentsRequest\x1a\".schedule.ListAppointmentsResponse\x12\\\n" +
	"\x11DeleteAppointment\x12\".schedule.DeleteAppointmentRequest\x1a#.schedule.DeleteAppointmentResponseB=Z;github.com/devhammed/grey-schedule/backend/proto;schedulepbb\x06proto3"

var (
	file_proto_appointment_proto_rawDescOnce sync.Once
	file_proto_appointment_proto_rawDescData []byte
)

func file_proto_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)))
	})
	return file_proto_appointment_proto_rawDescData
}

var file_proto_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_appointment_proto_goTypes = []any{
	(*Appointment)(nil),               // 0: schedule.Appointment
	(*CreateAppointmentRequest)(nil),  // 1: schedule.CreateAppointmentRequest
	(*CreateAppointmentResponse)(nil), // 2: schedule.CreateAppointmentResponse
	(*ListAppointmentsRequest)(nil),   // 3: schedule.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),  // 4: schedule.ListAppointmentsResponse
	(*DeleteAppointmentRequest)(nil),  // 5: schedule.DeleteAppointmentRequest
	(*DeleteAppointmentResponse)(nil), // 6: schedule.DeleteAppointmentResponse
}
var file_proto_appointment_proto_depIdxs = []int32{
	0, // 0: schedule.CreateAppointmentResponse.appointment:type_name -> schedule.Appointment
	0, // 1: schedule.ListAppointmentsResponse.appointments:type_name -> schedule.Appointment
	1, // 2: schedule.AppointmentService.CreateAppointment:input_type -> schedule.CreateAppointmentRequest
	3, // 3: schedule.AppointmentService.ListAppointments:input_type -> schedule.ListAppointmentsRequest
	5, // 4: schedule.AppointmentService.DeleteAppointment:input_type -> schedule.DeleteAppointmentRequest
	2, // 5: schedule.AppointmentService.CreateAppointment:output_type -> schedule.CreateAppointmentResponse
	4, // 6: schedule.AppointmentService.ListAppointments:output_type -> schedule.ListAppointmentsResponse
	6, // 7: schedule.AppointmentService.DeleteAppointment:output_type -> schedule.DeleteAppointmentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_appointment_proto_init() }
func file_proto_appointment_proto_init() {
	if File_proto_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointment_proto_depIdxs,
		MessageInfos:      file_proto_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointment_proto = out.File
	file_proto_appointment_proto_goTypes = nil
	file_proto_appointment_proto_depIdxs = nil
}
